### ISSUE TITLE
Some problem with sending push notifications 

### ISSUE THREAD

**Issue by ilyabochkov1331801** [klaviyo/klaviyo-swift-sdk#110]
### Description

Hello. One of the my colleagues report a problem and haven’t had any answer https://community.klaviyo.com/members/alena-n-14748. Looks like klaviyo sends pushes using sandbox endpoint because of we have same result using side service

### Checklist

- [ ] I have determined whether this bug is also reproducible in a vanilla SwiftUI project.
- [ ] If possible, I've reproduced the issue using the `main` branch of this package.
- [X] This issue hasn't been addressed in an [existing GitHub issue](https://github.com/klaviyo/klaviyo-swift-sdk/issues) or [discussion](https://github.com/pointfreeco/klaviyo/klaviyo-swift-sdk/discussions).

### The Klaviyo Swift SDK version information

2.2.1

### Destination operating system

iOS 16

**Comment by ndurell** [comment]
Hey there! We recently implemented sandbox support. We should only use the sandbox when the token is associated with a debug build. We haven't added a way to view this information in the UI but potentially if you can provide us with the token in question we can tell you which environment it is using.

**Comment by ilyabochkov1331801** [comment]
0a57d226fcdeefe957dd2e430cdccb4b9c0aa62ae44f5531a5f499e512efb9bf problem with this token. We got it from TestFlight build so there is a production token

**Comment by ilyabochkov1331801** [comment]
![IMG_3064](https://github.com/klaviyo/klaviyo-swift-sdk/assets/46449696/380300e7-f768-41fc-9c09-e58ca1efe02d)
![IMG_3065](https://github.com/klaviyo/klaviyo-swift-sdk/assets/46449696/97cc48b8-e48d-4ca8-bb7c-6079e8b8bc96)
![IMG_3066](https://github.com/klaviyo/klaviyo-swift-sdk/assets/46449696/d28ed0c2-44e9-4166-83f9-87aa501ed2d1)
Look at this screenshots 
1) error info from klaviyo (BadDeviceToken)
2) succeed sent push using same token and production environment 
3) failed push using sandbox (same error)

**Comment by ndurell** [comment]
Ahh got it ok I will check on this token.

**Comment by ajaysubra** [comment]
We are looking into this on our end @ilyabochkov1331801 in the mean time here is some thing you can try if you already haven't - 

Uninstall all debug and prod apps from the device and install just the test flight app and see if you are able to send a push. We released a new feature today that can be used to send a test push to a single device from the push content builder.  You can bring up this modal using the preview send button at the top right.
![image](https://github.com/klaviyo/klaviyo-swift-sdk/assets/118314354/61c2c76c-934e-4f82-910d-4f2f82b10150)

**Comment by ilyabochkov1331801** [comment]
It works now) 
I got notification using push preview and using compaign on the same build. I will ask QA to check and close issue if all will be fine
