### ISSUE TITLE
KlaviyoSDK().handle is always returning false

### ISSUE THREAD

**Issue by chaser79** [klaviyo/klaviyo-swift-sdk#114]
### Description

Im trying to implement deep linking using the KlaviyoSDK. I have implemented this method
```
public func userNotificationCenter(_ center: UNUserNotificationCenter, didReceive response: UNNotificationResponse, withCompletionHandler completionHandler: @escaping () -> Void) {
        let handled = KlaviyoSDK().handle(notificationResponse: response, withCompletionHandler: completionHandler) { url in
            print(url.absoluteString)
        }
        if !handled {
            completionHandler()
        }
    }
``` 

The url never gets printed and `handled` is always returning false. I have looked into this method and I think the cause is because the `_k` property is not part of the `body` on the `userInfo`. The notifications are being sent from Klaviyo. Is there any setting I need to set up to have the notification payload contain the `_k` key ?

I am running this in sandbox.

### Checklist

- [X] I have determined whether this bug is also reproducible in a vanilla SwiftUI project.
- [X] If possible, I've reproduced the issue using the `main` branch of this package.
- [X] This issue hasn't been addressed in an [existing GitHub issue](https://github.com/klaviyo/klaviyo-swift-sdk/issues) or [discussion](https://github.com/pointfreeco/klaviyo/klaviyo-swift-sdk/discussions).

### Expected behavior

The `KlaviyoSDK().handle` will return true and the `deepLinkHandler` would return the url.

### Actual behavior

The `KlaviyoSDK().handle` returns false and the `deepLinkHandler` never gets called.

### Steps to reproduce

Set up the handle methos in the userNotificationCenter didReceive delegate method. Send and notification from Klayvio.

### The Klaviyo Swift SDK version information

2.2.1

### Destination operating system

16.6

### Xcode version information

14.3

### Swift Compiler version information

```shell
1.75.2 Apple Swift version 5.8 (swiftlang-5.8.0.124.2 clang-1403.0.22.11.100)
```

**Comment by ajaysubra** [comment]
Hi @chaser79 thanks for reporting this. We are aware of this bug with sending previews from our web preview sending feature that we recently released.  We are working on a fix but in the mean time as a work around you can send using the actual campaign scheduling to a list/segment that only has your test tokens. 

Will keep this issue open until we fix the bug and report back.

**Comment by ajaysubra** [comment]
Hi @chaser79 we fixed the bug of `_k` not being sent from our sending pipelines when sending test previews. You should see the `KlaviyoSDK().handle` method return true now. You don't need to update you app since this was a backend fix.
