### ISSUE TITLE
Missing "Added to Cart" event

### ISSUE THREAD

**Issue by walkingbrad** [klaviyo/klaviyo-swift-sdk#119]
### Description

I'm new to Klaviyo, but neither the iOS nor Android SDKs have the "Added to Cart" event name/type available. You guys have plenty of [documentation](https://developers.klaviyo.com/en/docs/guide_to_integrating_a_platform_without_a_pre_built_klaviyo_integration) indicating it's a normal standard event (including JS examples for triggering it), so I'm confused.

Should we trigger it as a custom event? If so, what should the event name be? Other mobile event names look like `$viewed_product` whereas JS documentation shows event names like `Added to Cart`, so I'm also confused about the formatting differences.

### Checklist

- [X] I have determined whether this bug is also reproducible in a vanilla SwiftUI project.
- [X] If possible, I've reproduced the issue using the `main` branch of this package.
- [X] This issue hasn't been addressed in an [existing GitHub issue](https://github.com/klaviyo/klaviyo-swift-sdk/issues) or [discussion](https://github.com/pointfreeco/klaviyo/klaviyo-swift-sdk/discussions).

### Expected behavior

There is an explicit `addedToCart` event name.

### Actual behavior

There is none, while most if not all other events exist.

### The Klaviyo Swift SDK version information

2.2.1

### Destination operating system

iOS 17

### Xcode version information

Xcode 15

**Comment by jordan-griffin** [comment]
Hey, thanks for opening this issue, it's a good call-out that we're missing this from our event options in both our mobile SDKs currently. I've filed away a feature request for this change for a future update to the SDK.

In the interim, you can create an "Added to Cart" event through the custom event type in the SDK with the key "$added_to_cart". I believe that should translate to an "Added to Cart" event in Klaviyo. You can then set properties on this event like you would with any other integration: e.g: [Added to Cart tracking snippet for JavaScript](https://developers.klaviyo.com/en/v1-2/docs/guide-to-integrating-a-platform-without-a-pre-built-klaviyo-integration#added-to-cart-tracking-snippet)

**Comment by walkingbrad** [comment]
@jordan-griffin Awesome! Thanks for the quick reply. This is a totally workable solution until the next update comes. Thanks for the deets!

**Comment by evan-masseau** [comment]
Hello, we've rolled out a new release, `2.5` on swift and `1.4` on android to correct event names and remove some that should not have been added in the first place. We appreciate your bringing this inconsistency to our attention! Relevant code is in these PRs:

Swift SDK:
https://github.com/klaviyo/klaviyo-swift-sdk/pull/138

Android SDK:
https://github.com/klaviyo/klaviyo-android-sdk/pull/107
