### ISSUE TITLE
Push Token shows Null in profile after User Registration. 

### ISSUE THREAD

**Issue by plRohitkios** [klaviyo/klaviyo-swift-sdk#123]
### Description

I am calling User Registration event using following SDK method. And then call set push token

> `klaviyoSdk?.set(profile: Profile(email: email, phoneNumber: number, externalId: externalId))`
> `klaviyoSdk?.set(pushToken: localToken)`

if user is not doing any other action we are seeing Push Token as Null as soon as we check the registration event. 
If user does some activity by triggering other Klaviyo events the PushToken is reflecting. 
Attaching image for reference. Let me know if I need to do some thing else at code side to resolve it. 

<img width="756" alt="Screenshot 2023-12-06 at 12 50 12 PM" src="https://github.com/klaviyo/klaviyo-swift-sdk/assets/119562033/7f1226e8-d8ed-4d22-925e-d8fd4f265810">

### Checklist

- [ ] I have determined whether this bug is also reproducible in a vanilla SwiftUI project.
- [X] If possible, I've reproduced the issue using the `main` branch of this package.
- [X] This issue hasn't been addressed in an [existing GitHub issue](https://github.com/klaviyo/klaviyo-swift-sdk/issues) or [discussion](https://github.com/pointfreeco/klaviyo/klaviyo-swift-sdk/discussions).

### Expected behavior

As soon as the User Registration gets called and set token method is called push token should get reflected

### Steps to reproduce

I am calling User Registration event using following SDK method. 
> `klaviyoSdk?.set(profile: Profile(email: email, phoneNumber: number, externalId: externalId))`

And then call set push token

> `klaviyoSdk?.set(pushToken: localToken)`

### The Klaviyo Swift SDK version information

2.2.1

### Destination operating system

iOS 16.2

### Xcode version information

13

**Comment by ndurell** [comment]
IIRC we currently only add the push token to the opened push event. We can definitely look into adding it for all other custom events as well. Just to be sure though you should still see that the token is associated with your profile even though it is not in that event. Also note: we have updated some of the behavior for set profile in 2.3.0, so you shouldn't need to set the token again after setting profile.

**Comment by plRohitkios** [comment]
Hi @ndurell, 
Thank you for the response. Also as I was doing some trial and error adding the delay before calling `klaviyoSdk?.set(pushToken: localToken)` I am able to see token in the newly registered profile.

**Comment by ndurell** [comment]
Just to make sure we aren't confusing things. Are you saying you weren't seeing the token on the profile or in the event. These are actually two different things. Regardless you may want to try 2.3.0 as we fixed a bunch issues around set profile and set token.

**Comment by plRohitkios** [comment]
@ndurell the event is now showing token correctly after SDK update. hence closing this ticket.

**Comment by plRohitkios** [comment]
@ndurell the event is now showing token correctly after SDK update. hence closing this ticket.
