### ISSUE TITLE
`.ViewedProduct` event does not show up as 'Viewed Product' in dashboard

### ISSUE THREAD

**Issue by walkingbrad** [klaviyo/klaviyo-swift-sdk#124]
### Description

When sending the `.ViewedProduct` event, it shows up in the dashboard as a new duplicated '$viewed_product' event instead of the canonical 'Viewed Product' event. I assume this is the case for other events as well, though I'll check more soon. I'll also try out version 2.3.0 since it was just released.

This is obviously pretty bad, since it bifurcates analytics data and muddies up one's whole dashboard setup. 

### Checklist

- [ ] I have determined whether this bug is also reproducible in a vanilla SwiftUI project.
- [ ] If possible, I've reproduced the issue using the `main` branch of this package.
- [X] This issue hasn't been addressed in an [existing GitHub issue](https://github.com/klaviyo/klaviyo-swift-sdk/issues) or [discussion](https://github.com/pointfreeco/klaviyo/klaviyo-swift-sdk/discussions).

### Expected behavior

Events sent from the iOS SDK appear with normalized names like 'Viewed Product' in the dashboard so that they integrate with the events from other surfaces.

### Actual behavior

Events sent from the iOS SDK appear as dollar sign-prefixed snake case names like `$viewed_product` in the dashboard.

### Steps to reproduce

1. Send a `.ViewedProduct` event from the iOS SDK.
2. Go to your Klaviyo profile event history to see the event it sent

### The Klaviyo Swift SDK version information

2.2.1

### Destination operating system

iOS 17

### Xcode version information

15

**Comment by walkingbrad** [comment]
I notice Android has this same behavior, so maybe it is intentional for some reason.

**Comment by ndurell** [comment]
Hey there! Sorry for not getting back to you yesterday. We are looking into this and will get back to you soon.

**Comment by ndurell** [comment]
As a workaround for now do you mind using the Custom Event option for now with the correct event name. We will likely issue an SDK update soon with fixes for this and the added to cart event you reported. Sorry for the inconvenience!

**Comment by walkingbrad** [comment]
Thanks for the reply. No problem! 

I'm just trying to figure the system out still and how it all interconnects. So your guidance alone is super helpful.

**Comment by evan-masseau** [comment]
An update: we had an internal mixup about naming conventions, and will be rolling out a fix to both SDKs that will correct some event names. We will close this once the release is available. In the interim, the workaround is as Noah said to use `custom` event name with the properly formatted event name.

**Comment by evan-masseau** [comment]
Hello again, we are rolling out a two-phased fix to this problem in both SDKs. There will be a minor release, `2.5.0` for swift and `1.4.0` for android, to introduce new enums and deprecate the legacy ones. Then a major release to get rid of the erroneous ones event metric names. For anyone wishing to continue to use the old names, you can still use a Custom enum and specify any string you like. 

Swift SDK:
 #138 
#139 

Android SDK:
https://github.com/klaviyo/klaviyo-android-sdk/pull/107
https://github.com/klaviyo/klaviyo-android-sdk/pull/109
