### ISSUE TITLE
Unable to build SDK

### ISSUE THREAD

**Issue by harishvitta** [klaviyo/klaviyo-swift-sdk#151]
### Description

I am having an issue showing inside the framework. Having build issues
<img width="1274" alt="Screenshot 2024-01-31 at 1 34 27 PM" src="https://github.com/klaviyo/klaviyo-swift-sdk/assets/786101/0b94be75-f279-4a81-b8da-f97bccc7479a">

### Checklist

- [ ] I have determined whether this bug is also reproducible in a vanilla SwiftUI project.
- [ ] If possible, I've reproduced the issue using the `main` branch of this package.
- [X] This issue hasn't been addressed in an [existing GitHub issue](https://github.com/klaviyo/klaviyo-swift-sdk/issues) or [discussion](https://github.com/pointfreeco/klaviyo/klaviyo-swift-sdk/discussions).

**Comment by harishvitta** [comment]
@ajaysubra Can you please have a look into this issue?

**Comment by ndurell** [comment]
Can you also provide version details on xcode?

**Comment by harishvitta** [comment]
Xcode: 14.3.1

**Comment by ndurell** [comment]
Thanks and sorry for this will try to repro here and get a fix to you shortly.

**Comment by harishvitta** [comment]
Thank you. I have downloaded the latest version of Xcode, which resolved my issue. But people who are on older versions will face this issue.

**Comment by ajaysubra** [comment]
@harishvitta Thanks again for reporting this to us. We have since fixed this issue and will be releasing it next week. Closing this issue for now.

**Comment by ajaysubra** [comment]
@harishvitta As mentioned in the previous message we've made the fix and published two releases - `2.5.2` and `3.0.2` containing the fix. These releases should work on xcode 14.x. Thanks again for reporting the issue to us.

**Comment by harishvitta** [comment]
@ajaysubra Thank you for quick fix.
