### ISSUE TITLE
Module map file not found after installation on Mac M3

### ISSUE THREAD

**Issue by LuanNguyen-HnL** [klaviyo/klaviyo-swift-sdk#178]
### Checklist

- [X] I have read the [contributing guidelines](https://github.com/klaviyo/klaviyo-swift-sdk/blob/master/.github/CONTRIBUTING.md)
- [X] I have determined whether this bug is also reproducible in a vanilla SwiftUI project.
- [X] If possible, I've reproduced the issue using the `main` branch of this package.
- [X] This issue hasn't been addressed in an [existing GitHub issue](https://github.com/klaviyo/klaviyo-swift-sdk/issues) or [discussion](https://github.com/pointfreeco/klaviyo/klaviyo-swift-sdk/discussions).

### Description

When I install the SDK to my project, and when I run it with debug scheme, the Xcode show the error "Module map file .... not found"

### Expected behavior

Run the debug app successfully

### Actual behavior

The xcode showed this error
<img width="918" alt="Screenshot 2024-05-11 at 15 56 46" src="https://github.com/klaviyo/klaviyo-swift-sdk/assets/101781199/c5eed072-1215-43b3-8663-7cbb7ab90c79">

### Steps to reproduce

Follow the steps of readme

### The Klaviyo Swift SDK version information

2.2.1

### Destination operating system

MACOS 14.4.1

### Xcode version information

15.2

### Swift Compiler version information

```shell
5.10
```

**Comment by ajaysubra** [comment]
Hey @LuanNguyen-HnL thanks for reporting. We will take a look and get back to you soon.

**Comment by ajaysubra** [comment]
@LuanNguyen-HnL could you please let me know which dependency manager you are using? 

Also, can you try the [example app](https://github.com/klaviyo/klaviyo-swift-sdk/tree/master/Examples/KlaviyoSwiftExamples) (SPM or cocoapods) from this repository and see if you are able to reproduce the same issue?
