### ISSUE TITLE
Missing APS config to trigger background message listeners

### ISSUE THREAD

**Issue by cka29** [klaviyo/klaviyo-swift-sdk#186]
### Checklist

- [X] I have read the [contributing guidelines](https://github.com/klaviyo/klaviyo-swift-sdk/blob/master/.github/CONTRIBUTING.md)
- [X] I have determined whether this bug is also reproducible in a vanilla SwiftUI project.
- [X] If possible, I've reproduced the issue using the `main` branch of this package.
- [X] This issue hasn't been addressed in an [existing GitHub issue](https://github.com/klaviyo/klaviyo-swift-sdk/issues) or [discussion](https://github.com/pointfreeco/klaviyo/klaviyo-swift-sdk/discussions).

### Description

Hello!

I did not know where to raise this question, since this is related to iOS and the way the push notifications are sent from Klaviyo's backend.

When sending push notifications via Klaviyo Dashboard, the payload is missing a crucial key/value to let the iOS platform know if the push can be handled in the background and wake the application if it is in background/terminated. 

We are using flutter, but implemented this SDK on the native side. We can see that this works for android (thats why we know that this definitely works). Here is an [issue](https://github.com/firebase/flutterfire/issues/10603) where some details are discussed.

Would it be possible to add this 
```
"content-available" : 1
```
to the notifications payload in order to trigger a background handler for iOS devices? Here is an example from firebase docs:
https://github.com/firebase/flutterfire/blob/master/packages/firebase_messaging/firebase_messaging/example/scripts/send-message.js#L37

I hope you can help us out here! Thank you 😊 

### Expected behavior

Sending a push notification from Klaviyos Dashboard to iOS devices triggers this native handler and can wake the app from a suspended state.

https://developer.apple.com/documentation/uikit/uiapplicationdelegate/1623013-application

### Actual behavior

Sending a push notification from Klaviyos Dashboard to iOS devices DOES not trigger this native handler. Instead the application has to be in the foreground/background.

https://developer.apple.com/documentation/uikit/uiapplicationdelegate/1623013-application

### Steps to reproduce

1. Send push notification from Klaviyo Dashboard to any iOS device 
2. [Native handler ](https://developer.apple.com/documentation/uikit/uiapplicationdelegate/1623013-application) is NOT triggered when the app is in a suspended state

### The Klaviyo Swift SDK version information

3.0.1

### Destination operating system

iOS 17

### Xcode version information

15.3

### Swift Compiler version information

```shell
swift-driver version: 1.90.11.1 Apple Swift version 5.10 (swiftlang-5.10.0.13 clang-1500.3.9.4)
Target: arm64-apple-macosx14.0
```

**Comment by ndurell** [comment]
Hi Cem,
Thanks for raising this issue. Unfortunately at this time we don't have support for background push on iOS. This is something that is on the roadmap and we've made some steps towards supporting it but we don't yet have a timeline for when it will be released. 

Thanks,
Noah

**Comment by cka29** [comment]
> Hi Cem, Thanks for raising this issue. Unfortunately at this time we don't have support for background push on iOS. This is something that is on the roadmap and we've made some steps towards supporting it but we don't yet have a timeline for when it will be released.
> 
> Thanks, Noah

@ndurell Are there any updates regarding this for Q4/Q1?
