### ISSUE TITLE
Soft unsubscribe particular device

### ISSUE THREAD

**Issue by Jack25apr** [klaviyo/klaviyo-swift-sdk#219]
### Checklist

- [X] I have read the [contributing guidelines](https://github.com/klaviyo/klaviyo-swift-sdk/blob/master/.github/CONTRIBUTING.md)
- [X] This issue hasn't been addressed in an [existing issue](https://github.com/klaviyo/klaviyo-swift-sdk/issues) or [pull request](https://github.com/klaviyo/klaviyo-swift-sdk/pulls)

### Description

```markdown
Hi!
Is it possible to add such feature:
Use Case:
We want to have possibility to "soft unsubscribe" particular device,
without creating custom properties and filtering during campaign creation, not for the WHOLE profile, but for particular device.

Currently we have toggle button in our app, that allows disabling push notification for particular device.
Also we have additional push notifications services(i.e. customer support chat) and we CANT just guide user to disallow all push notifications for the whole app.
```

### Proposed Solution

```markdown
Make possibility to override `enablement_status` when sending pushToken for example.
For now we always sending real subscription status aka `enablement_status`


//  Klaviyo.swift
...
 public func set(pushToken: String) {
        Task {
            let enablement = await environment.getNotificationSettings()
            dispatchOnMainThread(action: .setPushToken(pushToken, enablement))
        }
    }
```
```


### Alternatives Considered

Or add separate specific call for overriding enablement_status
Or add separate field for device and consider new device field if it is set and its ON/ALLOWED/AUTHORISED when sending push notifications.

### Additional Context

_No response_

**Comment by Jack25apr** [comment]
### Alternatives Considered
Or add separate specific call for overriding enablement_status
Or add separate field for device and consider new device field if it is set and its ON/ALLOWED/AUTHORISED when sending push notifications.

**Comment by ajaysubra** [comment]
Hey @Jack25apr Thank for the feature request. As indicated, this is not something we support and not on our near term road map but something we will consider in the future.
