### ISSUE TITLE
Question: Are you planning on adding SPM support?

### ISSUE THREAD

**Issue by cameronehrlich** [klaviyo/klaviyo-swift-sdk#29]
Hello!
We are investigating moving our project to SPM, and `KlaviyoSwift` is our only dependency that doesn't explicitly support SPM.
Any plans on adding support?

**Comment by vvit** [comment]
Agree, I've been surprised that SPM is not supported. Please 🙏

**Comment by ndurell** [comment]
This is out now. You can use version 1.5.1 with SPM. Let me know if you have any issues or questions on it!
