### ISSUE TITLE
Any chance to update to swift 3.0 ?

### ISSUE THREAD

**Issue by Qiki** [klaviyo/klaviyo-swift-sdk#3]
I am using the klaviyo swift sdk for push notification, so just wonder any chance we can update to use swift 3.0? =)

@Khinkle14

**Comment by JacobPritchettBB** [comment]
@Khinkle14 Any updates on this? I'm also hoping to use this with Swift 3.0, especially since Apple has dropped support for Swift 2.x in the latest Xcode updates.

**Comment by ndurell** [comment]
Our 1.4.2 should support swift 3.
We also recently updated the SDK to swift 4.2.
