### ISSUE TITLE
How about the Objective-C Project?

### ISSUE THREAD

**Issue by LuanNguyenHNL** [klaviyo/klaviyo-swift-sdk#53]
Hi the owner, Is the klaviyo-objc-sdk same as this lib? It was not updated for 7 years? @@

**Comment by ndurell** [comment]
The two SDKs are similar, but there are some small differences in functionality. We are planning to more actively maintain the Swift SDK going forward due to Swift being a more popular language than Objective-C at this point. Are you currently using the klaviyo-objc-sdk?

**Comment by LuanNguyenHNL** [comment]
> The two SDKs are similar, but there are some small differences in functionality. We are planning to more actively maintain the Swift SDK going forward due to Swift being a more popular language than Objective-C at this point. Are you currently using the klaviyo-objc-sdk?

THanks for the reply. I am wondering to use 1 of 2 SDKs for my React Native project. Do you have any suggestions for me?

**Comment by ndurell** [comment]
I haven't seen your project but would recommend this one over objc for now.

**Comment by LuanNguyenHNL** [comment]
> I haven't seen your project but would recommend this one over objc for now.

Ya, my project is using objective-c. I will try to use this one. Thanks!

**Comment by ndurell** [comment]
Let me know if you run into any issues. Happy to help out if needed!

**Comment by Milanp24** [comment]
I have created a react native package for Klaviyo Swift SDK for our RN project which is using Objective c. 
I am using package to set pushToken to Klaviyo SDK.
I have device token in string which is provided by PushNotificationIOS in JS code but Klaviyo SDK accepts Data .

I tried Data(token.utf8) but this is generating bad token.
