### ISSUE TITLE
Unable to send push notification

### ISSUE THREAD

**Issue by LuanNguyenHNL** [klaviyo/klaviyo-swift-sdk#55]
Hi @ndurell, I've setup push notification as this link https://help.klaviyo.com/hc/en-us/articles/360023213971, but when i ran 1 flow to trigger the push notification. It skipped with the reason 'Unable to send push notification'. Can I test this with the local build or testflight build? Does the app need to be published to App Store? please help! THanks
<img width="980" alt="Screenshot 2023-01-18 at 11 20 17" src="https://user-images.githubusercontent.com/101781199/213083203-284181c7-80ce-4027-b7fe-aaf722e0d970.png">

**Comment by ndurell** [comment]
That's great you got this much setup! Yes you will need to deploy to test flight to test it out. We don't have support for sandbox as of yet.

**Comment by LuanNguyenHNL** [comment]
> That's great you got this much setup! Yes you will need to deploy to test flight to test it out. We don't have support for sandbox as of yet.

Yes, thank you very much! Will get back if needed!
